[window]

opacity = 0.9
# blur = true

padding.x = 5
padding.y = 5

decorations = "Buttonless"

option_as_alt = "Both"


[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 11.0

